/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Shell3dLabRouteImport } from './routes/_shell.3d-lab'
import { Route as ShellAiModelsRouteImport } from './routes/_shell.ai-models'
import { Route as ShellAutomationsRouteImport } from './routes/_shell.automations'
import { Route as ShellChatRouteImport } from './routes/_shell.chat'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDocumentsRouteImport } from './routes/_shell.documents'
import { Route as ShellIotRoboticsRouteImport } from './routes/_shell.iot-robotics'
import { Route as ShellMemoryRouteImport } from './routes/_shell.memory'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellProjectsRouteImport } from './routes/_shell.projects'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSimulationsRouteImport } from './routes/_shell.simulations'
import { Route as ShellVisionCameraRouteImport } from './routes/_shell.vision-camera'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Shell3dLabRoute = Shell3dLabRouteImport.update({
  id: '/3d-lab',
  path: '/3d-lab',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiModelsRoute = ShellAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAutomationsRoute = ShellAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatRoute = ShellChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIotRoboticsRoute = ShellIotRoboticsRouteImport.update({
  id: '/iot-robotics',
  path: '/iot-robotics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMemoryRoute = ShellMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsRoute = ShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSimulationsRoute = ShellSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVisionCameraRoute = ShellVisionCameraRouteImport.update({
  id: '/vision-camera',
  path: '/vision-camera',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/3d-lab': typeof Shell3dLabRoute
  '/ai-models': typeof ShellAiModelsRoute
  '/automations': typeof ShellAutomationsRoute
  '/chat': typeof ShellChatRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/iot-robotics': typeof ShellIotRoboticsRoute
  '/memory': typeof ShellMemoryRoute
  '/profile': typeof ShellProfileRoute
  '/projects': typeof ShellProjectsRoute
  '/settings': typeof ShellSettingsRoute
  '/simulations': typeof ShellSimulationsRoute
  '/vision-camera': typeof ShellVisionCameraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/3d-lab': typeof Shell3dLabRoute
  '/ai-models': typeof ShellAiModelsRoute
  '/automations': typeof ShellAutomationsRoute
  '/chat': typeof ShellChatRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/iot-robotics': typeof ShellIotRoboticsRoute
  '/memory': typeof ShellMemoryRoute
  '/profile': typeof ShellProfileRoute
  '/projects': typeof ShellProjectsRoute
  '/settings': typeof ShellSettingsRoute
  '/simulations': typeof ShellSimulationsRoute
  '/vision-camera': typeof ShellVisionCameraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_shell/3d-lab': typeof Shell3dLabRoute
  '/_shell/ai-models': typeof ShellAiModelsRoute
  '/_shell/automations': typeof ShellAutomationsRoute
  '/_shell/chat': typeof ShellChatRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/iot-robotics': typeof ShellIotRoboticsRoute
  '/_shell/memory': typeof ShellMemoryRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/projects': typeof ShellProjectsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/simulations': typeof ShellSimulationsRoute
  '/_shell/vision-camera': typeof ShellVisionCameraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/3d-lab'
    | '/ai-models'
    | '/automations'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/iot-robotics'
    | '/memory'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/simulations'
    | '/vision-camera'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/3d-lab'
    | '/ai-models'
    | '/automations'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/iot-robotics'
    | '/memory'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/simulations'
    | '/vision-camera'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/forgot-password'
    | '/reset-password'
    | '/signup'
    | '/_shell/3d-lab'
    | '/_shell/ai-models'
    | '/_shell/automations'
    | '/_shell/chat'
    | '/_shell/dashboard'
    | '/_shell/documents'
    | '/_shell/iot-robotics'
    | '/_shell/memory'
    | '/_shell/profile'
    | '/_shell/projects'
    | '/_shell/settings'
    | '/_shell/simulations'
    | '/_shell/vision-camera'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/3d-lab': {
      id: '/_shell/3d-lab'
      path: '/3d-lab'
      fullPath: '/3d-lab'
      preLoaderRoute: typeof Shell3dLabRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai-models': {
      id: '/_shell/ai-models'
      path: '/ai-models'
      fullPath: '/ai-models'
      preLoaderRoute: typeof ShellAiModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/automations': {
      id: '/_shell/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ShellAutomationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat': {
      id: '/_shell/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ShellChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/iot-robotics': {
      id: '/_shell/iot-robotics'
      path: '/iot-robotics'
      fullPath: '/iot-robotics'
      preLoaderRoute: typeof ShellIotRoboticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/memory': {
      id: '/_shell/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof ShellMemoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects': {
      id: '/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ShellProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/simulations': {
      id: '/_shell/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof ShellSimulationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vision-camera': {
      id: '/_shell/vision-camera'
      path: '/vision-camera'
      fullPath: '/vision-camera'
      preLoaderRoute: typeof ShellVisionCameraRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  Shell3dLabRoute: typeof Shell3dLabRoute
  ShellAiModelsRoute: typeof ShellAiModelsRoute
  ShellAutomationsRoute: typeof ShellAutomationsRoute
  ShellChatRoute: typeof ShellChatRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellIotRoboticsRoute: typeof ShellIotRoboticsRoute
  ShellMemoryRoute: typeof ShellMemoryRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellProjectsRoute: typeof ShellProjectsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSimulationsRoute: typeof ShellSimulationsRoute
  ShellVisionCameraRoute: typeof ShellVisionCameraRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  Shell3dLabRoute: Shell3dLabRoute,
  ShellAiModelsRoute: ShellAiModelsRoute,
  ShellAutomationsRoute: ShellAutomationsRoute,
  ShellChatRoute: ShellChatRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellIotRoboticsRoute: ShellIotRoboticsRoute,
  ShellMemoryRoute: ShellMemoryRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellProjectsRoute: ShellProjectsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSimulationsRoute: ShellSimulationsRoute,
  ShellVisionCameraRoute: ShellVisionCameraRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
